In [ ]:
import torch

In [ ]:
torch.manual_seed(42)
x = torch.rand(7,7)
x

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

In [ ]:
torch.manual_seed(42)
y = torch.rand(1,7)
torch.mm(x, y.T)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [ ]:
random_seed = 0

torch.manual_seed(random_seed)
a = torch.rand(7, 7)

torch.manual_seed(random_seed)
b = torch.rand(1, 7)

print(torch.mm(a, b.T))

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
#creating 2 tensors and sending them to GPU

torch.manual_seed(1234)
c = torch.rand(2,3)

torch.manual_seed(1234)
d = torch.rand(2,3)

c_cuda = c.to("cuda")
d_cuda = d.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
#matrix multiplication

e = c_cuda @ d_cuda.T

In [ ]:
#min and max
print(f"The smallest value in e (the matrix multiplication) is {e.min()}")
print(f"The largest value in e (the matrix multiplication) is {e.max()}")

In [ ]:
torch.manual_seed(7)
g = torch.rand(1,1,1,10)

g_squeezed = g.squeeze()

print(g_squeezed[0])
print(g_squeezed[0].shape)
print(g_squeezed[1].size())