<a href="https://colab.research.google.com/github/Theoph-ay/pytorch_tutorials/blob/pytorch_learning/Pytorch_fundermentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
#creating tensors
scalar = torch.tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
tens = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tens

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tens.shape

torch.Size([2, 3, 3])

In [15]:
#random tensors size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7013, 0.4364, 0.9558, 0.8705],
        [0.6251, 0.6393, 0.2165, 0.6188],
        [0.3558, 0.2333, 0.8173, 0.6937]])

In [16]:
#random tensors for image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel ( R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
#create tensors of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#create tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#creating a range of tensors and tensors-like
n_range=torch.arange(1, 11, 2)
n_range



tensor([1, 3, 5, 7, 9])

In [20]:
five_zeros = torch.zeros_like(input=n_range)
five_zeros

tensor([0, 0, 0, 0, 0])

In [21]:
range_ones = torch.ones_like(input=n_range)
range_ones

tensor([1, 1, 1, 1, 1])

In [22]:
#tensor data types
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

getting informations from tensors

* data_type = "tensor.shape"
* shape = "tensor.shape"
* device = "tensor.device"
* shape= torch.shape or tensor.size




In [24]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6119, 0.7116, 0.0037, 0.2169],
        [0.2233, 0.8840, 0.7531, 0.7990],
        [0.7937, 0.9270, 0.4059, 0.0539]])

In [25]:
some_tensor.shape, some_tensor.size(), some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'), torch.float32)

### manipulating tensors
operations
* Matrix Multiplication
* Other mathematical operations additions and the like

## Rule for Matrix multiplication
1. The inner dimensions must match:
* ( 3,2) @ (3,2) won't work (@ is another function for matrix multiplication like torch.matmul, e.g tensor 2 tensor)

* (3,2) @ (2,3) will work
* (2,3) @ (3,2) will work

2. THe resulting matrix has the shape of the **outer dimenstions**:

* (2,3) @ (3,2) -> (2,3)
* (3,2) @ (2,3) -> (3,3)


In [38]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8592, 1.0438, 1.2481],
        [0.8902, 1.1404, 1.3019],
        [0.2959, 0.5363, 0.4562]])

In [26]:
tensor = torch.tensor([1,2,3])
tensor * 10, tensor -10

(tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [27]:
#in-built torch tensor multiplication and addition
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [28]:
#elementwise multiplication
tensor * tensor

tensor([1, 4, 9])

In [29]:
#Matrix Multiplication
tensor.matmul(tensor)

tensor(14)

In [30]:
#calculation by hand
1*1 + 2*2 + 3*3

14

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
print(type(tensor))

<class 'torch.Tensor'>


In [33]:
print(torch.tensor)

<built-in method tensor of type object at 0x7dc5294f74a0>


In [34]:
%%time
tensor = torch.tensor([1,2,3])
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 982 µs, sys: 0 ns, total: 982 µs
Wall time: 1.24 ms


In [35]:
%%time
torch.sum(tensor * tensor)

CPU times: user 476 µs, sys: 0 ns, total: 476 µs
Wall time: 529 µs


tensor(14)

In [36]:
%%time
#Using pytorch inbuilt function, to compare the time

torch.matmul(tensor, tensor)

CPU times: user 404 µs, sys: 52 µs, total: 456 µs
Wall time: 933 µs


tensor(14)

### Shape Error

In [39]:
#shapes for matrix mulriplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm is an alias for torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## Transposr Tensors
Helps to fix shape issues, changes the dimensions

```
tensor.T
```

In [41]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [42]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
#Rule 1 and Rule 2
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])