In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [ ]:
#creating tensors
scalar = torch.tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
tens = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tens

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tens.shape

torch.Size([2, 3, 3])

In [ ]:
#random tensors size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1188, 0.7880, 0.8378, 0.7479],
        [0.5743, 0.8092, 0.4077, 0.5845],
        [0.8008, 0.2238, 0.7214, 0.1825]])

In [ ]:
#random tensors for image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel ( R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#create tensors of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#creating a range of tensors and tensors-like
n_range=torch.arange(1, 11, 2)
n_range



tensor([1, 3, 5, 7, 9])

In [ ]:
five_zeros = torch.zeros_like(input=n_range)
five_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
range_ones = torch.ones_like(input=n_range)
range_ones

tensor([1, 1, 1, 1, 1])

In [ ]:
#tensor data types
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

getting informations from tensors

* data_type = "tensor.shape"
* shape = "tensor.shape"
* device = "tensor.device"
* shape= torch.shape or tensor.size




In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5900, 0.6696, 0.3604, 0.1840],
        [0.0610, 0.9424, 0.4375, 0.6525],
        [0.6256, 0.7274, 0.8473, 0.4555]])

In [ ]:
some_tensor.shape, some_tensor.size(), some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'), torch.float32)

### manipulating tensors
operations
* Matrix Multiplication
* Other mathematical operations additions and the like

## Rule for Matrix multiplication
1. The inner dimensions must match:
* ( 3,2) @ (3,2) won't work (@ is another function for matrix multiplication like torch.matmul, e.g tensor 2 tensor)

* (3,2) @ (2,3) will work
* (2,3) @ (3,2) will work

2. THe resulting matrix has the shape of the **outer dimenstions**:

* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)


In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8537, 0.5346, 0.7596],
        [0.7349, 0.4596, 0.6537],
        [0.8569, 0.5013, 0.7529]])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor * 10, tensor -10

(tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [ ]:
#in-built torch tensor multiplication and addition
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [ ]:
#elementwise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#Matrix Multiplication
tensor.matmul(tensor)

tensor(14)

In [ ]:
#calculation by hand
1*1 + 2*2 + 3*3

14

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
print(type(tensor))

<class 'torch.Tensor'>


In [ ]:
print(torch.tensor)

<built-in method tensor of type object at 0x79b892ae5c40>


In [ ]:
%%time
tensor = torch.tensor([1,2,3])
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.28 ms, sys: 45 µs, total: 1.33 ms
Wall time: 1.51 ms


In [ ]:
%%time
torch.sum(tensor * tensor)

CPU times: user 238 µs, sys: 37 µs, total: 275 µs
Wall time: 215 µs


tensor(14)

In [ ]:
%%time
#Using pytorch inbuilt function, to compare the time

torch.matmul(tensor, tensor)

CPU times: user 398 µs, sys: 63 µs, total: 461 µs
Wall time: 2.79 ms


tensor(14)

### Shape Error

In [ ]:
#shapes for matrix mulriplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm is an alias for torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## Transposr Tensors
Helps to fix shape issues, changes the dimensions

```
tensor.T
```

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
#Rule 1 and Rule 2
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

Finding the min, max, sum (Tensor Aggregation)

In [ ]:
#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean - note the torch.mean() function requires a tensror of float 32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#finding the positional min and max
x.argmin(), x.argmax()

(tensor(0), tensor(9))

#3 Reshaping, stacking, squeezing and unsqueexing tensors
* Reshaping - reshapes an input to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all "1"dimensions from a tensor
* Unsqueeze - add a '1'dimension to a target tensor
*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
#Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x cos a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
u =torch.rand(3,3,1)
u

tensor([[[0.0222],
         [0.4735],
         [0.4711]],

        [[0.0382],
         [0.4620],
         [0.2697]],

        [[0.1208],
         [0.2438],
         [0.1197]]])

In [ ]:
u_squeezed = u.squeeze()
u_squeezed

tensor([[0.0222, 0.4735, 0.4711],
        [0.0382, 0.4620, 0.2697],
        [0.1208, 0.2438, 0.1197]])

In [ ]:
# torch.unsqueeze() adds a single dimension to a targt tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute() rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

#permute the original tensor to rearrange the acis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing
Indexing  with Pytorch us similar to indexing with Numpy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#let's index on our new tensor
x[0 ]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#in dex on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# : to select "all" of target dim
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#get all value of zeroth and first dim and only only index 1 of 2nd dimension
x[:,0, :]


tensor([[1, 2, 3]])

In [ ]:
x[0,:, 2]

tensor([3, 6, 9])

## Pytorch tensors and numpy

#data from numoy to pytorch tensors -> torch.from_numpy(ndarray)
#pytorch tensor to numpy -> torch.Tensor.numpy()


In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #cos numpy is float64, it returns float 64 tensor, but base tensor type is float 32, so you can use .type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

## reproducibility

**set random seed**

In [ ]:
import torch

#two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.5401, 0.6252, 0.7271, 0.1572],
        [0.9670, 0.2177, 0.6798, 0.5876],
        [0.6336, 0.7888, 0.7373, 0.4184]])
tensor([[0.1479, 0.2871, 0.2483, 0.4365],
        [0.2288, 0.1635, 0.7936, 0.2823],
        [0.1396, 0.8521, 0.9096, 0.7881]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#random but reproducible tensors
import torch


#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Sat Jan  3 11:28:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
#set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

#putting tensors and models on gpu

In [ ]:
#creat a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

#3 moving tensors back to CPU


In [ ]:
#tensor  to numpy
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])