<a href="https://colab.research.google.com/github/Theoph-ay/pytorch_tutorials/blob/pytorch_learning/Pytorch_fundermentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [46]:
#creating tensors
scalar = torch.tensor(7)

In [47]:
scalar.ndim

0

In [48]:
#get tensor back as python int
scalar.item()

7

In [49]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [50]:
vector.ndim

1

In [51]:
vector.shape

torch.Size([2])

In [52]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [53]:
MATRIX[1]

tensor([ 9, 10])

In [54]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

In [57]:
tens = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                     [[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tens

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [58]:
tens.shape

torch.Size([2, 3, 3])

In [59]:
#random tensors size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0549, 0.8716, 0.4714, 0.8540],
        [0.5006, 0.0413, 0.7304, 0.9489],
        [0.3549, 0.9800, 0.5832, 0.3535]])

In [60]:
#random tensors for image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel ( R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [61]:
#create tensors of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
#create tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
#creating a range of tensors and tensors-like
range=torch.arange(1, 11, 2)
range



tensor([1, 3, 5, 7, 9])

In [64]:
five_zeros = torch.zeros_like(input=range)
five_zeros

tensor([0, 0, 0, 0, 0])

In [65]:
range_ones = torch.ones_like(input=range)
range_ones

tensor([1, 1, 1, 1, 1])

In [66]:
#tensor data types
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
#getting informations from tensors
#data_type = "tensor.shape"
#shape = "tensor.shape"
#device = "tensor.device"
#shape= torch.shape or tensor.size

In [69]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9041, 0.7337, 0.7063, 0.3908],
        [0.9628, 0.5553, 0.8294, 0.8331],
        [0.8262, 0.4068, 0.0358, 0.0508]])

In [70]:
some_tensor.shape, some_tensor.size(), some_tensor.device, some_tensor.dtype

(torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'), torch.float32)

### manipulating tensors
operations
* Matrix Multiplication
* Other mathematical operations additions and the like

In [71]:
tensor = torch.tensor([1,2,3])
tensor * 10, tensor -10

(tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [72]:
#in-built torch tensor multiplication and addition
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [73]:
#elementwise multiplication
tensor * tensor

tensor([1, 4, 9])

In [74]:
#Matrix Multiplication
tensor.matmul(tensor)

tensor(14)

In [75]:
#calculation by hand
1*1 + 2*2 + 3*3

14

In [76]:
tensor

tensor([1, 2, 3])

In [77]:
print(type(tensor))

<class 'torch.Tensor'>


In [78]:
print(torch.tensor)

<built-in method tensor of type object at 0x7d0d8caf74a0>


In [79]:
print(x)
print(type(x))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [80]:
%%time
x = torch.tensor([1, 2, 3])
value = 0
for i in range(len(x)):
    value += x[i] * x[i]
print(value)

TypeError: 'Tensor' object is not callable